services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003" # El puerto interno de tu contenedor
    environment:
      NODE_ENV: production
      PORT: 3003
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
